.386P
INCLUDE STRUKT.TXT
DANE    SEGMENT USE16
	GDT_NULL 	DESKR <0,0,0,0,0,0>
	GDT_DANE 	DESKR <DANE_SIZE-1,0,0,92H,0,0>		;8
	GDT_PROGRAM DESKR <PROGRAM_SIZE-1,0,0,98H,0,0>		;16
	GDT_STOS 	DESKR <767,0,0,92H,0,0>			;24
	GDT_EKRAN 	DESKR <4095,8000H,0BH,92H,0,0>		;32
	GDT_TSS_0	DESKR <103,0,0,89H,0,0>			;40
	GDT_TSS_1	DESKR <103,0,0,89H,0,0>			;48
	GDT_TSS_2	DESKR <103,0,0,89H,0,0>			;56
	GDT_HIMEM	DESKR <0FFFFh,0,20H,92H,00H,0> 		;segment 64kB
	GDT_SIZE = $ - GDT_NULL 
;Tablica deskryptorow przerwan IDT
	IDT	LABEL WORD
	INCLUDE PM_IDT.TXT
	IDT_0	INTR <PROC_0>
	IDT_1	INTR <PROC_1>
	IDT_SIZE = $ - IDT
	PDESKR	DQ 	0
	ORG_IDT	DQ	0
	TEKST	DB 'TRYB CHRONIONY'
   	INCLUDE PM_DATA.TXT
	INFO	DB 'POWROT Z TRYBU CHRONIONEGO $'
	T0_ADDR	DW 0,40
	T1_ADDR	DW 0,48
	T2_ADDR	DW 0,56
	TSS_0	DB 104 DUP (0)
	TSS_1	DB 104 DUP (0)
	TSS_2	DB 104 DUP (0)
	GWIAZDKA	DB '*'
	A20	DB 0
	FAST_A20 DB 0

	POZYCJA_GWIAZDKI DW 0
	POROWNYWANIE_GWIAZDKI DW 78
	KOLOR_GWIAZDKI DB 01H
	
	TIM_SEC	DW 0
	TIM_MIN	DW 0
	TIM_H	DW 0
	DZIELNIK DB 10
	
DANE_SIZE=$-GDT_NULL
DANE	ENDS

PROGRAM	SEGMENT 'CODE' USE16
        ASSUME CS:PROGRAM, DS:DANE, SS:STK
POCZ	LABEL WORD
INCLUDE PM_EXC.TXT
INCLUDE MAKRA.TXT
PROC_0	PROC
PROC_0	ENDP
;Procedura obslugi przerwania od klawiatury (przerwanie nr 1)
PROC_1	PROC
	PUSH AX
	PUSH DX
	IN AL,60H	;Pobranie kodu klawisza
	MOV DL,AL
	IN AL,61H	;Potwierdzenie pobrania numeru klawisza
	OR AL,80H
	OUT 61H,AL
	AND AL,7FH
	OUT 61H,AL
	MOV AL,20H	;Sygnal konca obslugi przerwania
	OUT 20H,AL
	CMP DL,2	;Klawisz '1'
	JE TSK0
	CMP DL,3	;Klawisz '2'
	JE TSK1
	CMP DL,0BH	;Klawisz '0'
	JE TSK2
	JMP OUT_P1
   TSK0:	JMP DWORD PTR T0_ADDR	;Przelaczenie zadania na zadanie 
					;nr 0 (program glowny)
	JMP out_p1
   TSK1:	JMP DWORD PTR T1_ADDR	;Przelaczenie zadania na zadanie nr 1
	JMP OUT_P1
   TSK2:	JMP DWORD PTR T2_ADDR	;Przelaczenie zadania na zadanie nr 2
   OUT_P1:	POP DX
	POP AX
	IRETD
PROC_1	ENDP

START:	
	CZY_DOSTEPNY_FAST_A20
	INICJOWANIE_DESKRYPTOROW
   PM_TSS0_I_TSS1 TSS_0,TSS_1,GDT_TSS_0,GDT_TSS_1
	XOR EAX,EAX
	MOV AX,OFFSET TSS_2
	ADD EAX,EBP
	MOV BX,OFFSET GDT_TSS_2
	MOV [BX].BASE_1,AX
	ROL EAX,16
	MOV [BX].BASE_M,AL
	MOV WORD PTR TSS_1+4CH,16		
	MOV WORD PTR TSS_1+20H,OFFSET ZADANIE1
	MOV WORD PTR TSS_1+50H,24		
	MOV WORD PTR TSS_1+38H,256
	MOV WORD PTR TSS_1+54H,8
	MOV WORD PTR TSS_1+48H,32
	STI		; ustawienie znacznika zestawienia na przerwanie
	PUSHFD		; przeslanie znacznikow na szczyt stosu
	POP EAX
	MOV DWORD PTR TSS_1+24H,EAX
	MOV WORD PTR TSS_2+4CH,16		
	MOV WORD PTR TSS_2+20H,OFFSET ZADANIE2
	MOV WORD PTR TSS_2+50H,24		
	MOV WORD PTR TSS_2+38H,512
	MOV WORD PTR TSS_2+54H,8
	MOV WORD PTR TSS_2+48H,32
	MOV DWORD PTR TSS_2+24H,EAX

	CLI
	INICJACJA_IDTR
	KONTROLER_PRZERWAN_PM 0FDH
	A20_ON
	AKTYWACJA_PM
	MOV AX,32
	MOV ES,AX
	MOV GS,AX
	MOV FS,AX
	MOV AX,40			;Zaladowanie rejestru zadania (TR)
	LTR AX				;deskryptorem segmentu stanu 
;zrobienie przedzialka
   	PRZEDZIALEK


   WYPISZ_N_ZNAKOW_Z_ATRYBUTEM TEKST,14,704,ATRYB
	STI
   C1:
;opoznienie
	DELAY 27

	ADD TIM_SEC, 1
	CMP TIM_SEC, 60
	JE  C2
	JMP C_WYSW
; byla minuta
   C2:	MOV TIM_SEC, 0
	ADD TIM_MIN, 1
	CMP TIM_MIN, 60
	JE  C3
	JMP C_WYSW
; byla godzina
   C3:	MOV TIM_MIN,0
	ADD TIM_H, 1
	CMP TIM_H, 24
	JE  C4
	JMP C_WYSW
   C4:  MOV TIM_H, 0
;====== wyswietlanie zegara
   C_WYSW:				;wyswietlanie zegara, ale jeszcze nie ogarniete
	
;====== sekundy
	MOV AX, TIM_SEC	
						;wypisanie sekundy dziesietnej
	DIV DZIELNIK
	ADD AL, 48
	MOV AH,71H			;kolor
	MOV BX,910			
	MOV ES:[BX],AX

  	MOV AX,TIM_SEC		;wypisanie sekundy jednosci
	DIV DZIELNIK
	MUL DZIELNIK	
	MOV BX, AX
	MOV AX,TIM_SEC	
	SUB AX, BX
	ADD AL, 48
	MOV AH,71H			;kolor
	MOV BX,912			
	MOV ES:[BX],AX
;====== dwukropek
	MOV AL, 58
	MOV AH,71H			;kolor
	MOV BX,908			
	MOV ES:[BX],AX

;====== minuty

	MOV AX, TIM_MIN	
				;wypisanie minuty dziesietnej
	DIV DZIELNIK
	ADD AL, 48
	MOV AH,71H			;kolor
	MOV BX,904			
	MOV ES:[BX],AX

  	MOV AX,TIM_MIN		;wypisanie minuty jednosci
	DIV DZIELNIK
	MUL DZIELNIK	
	MOV BX, AX
	MOV AX,TIM_MIN	
	SUB AX, BX
	ADD AL, 48
	MOV AH,71H		;kolor
	MOV BX,906			
	MOV ES:[BX],AX

;====== dwukropek
	MOV AL, 58
	MOV AH,71H		;kolor
	MOV BX,902			
	MOV ES:[BX],AX

;====== godziny
	MOV AX, TIM_H	
				;wypisanie godziny dziesietnej
	DIV DZIELNIK
	ADD AL, 48
	MOV AH,71H		;kolor
	MOV BX,900			
	MOV ES:[BX],AX

  	MOV AX,TIM_H	;wypisanie godziny jednosci
	DIV DZIELNIK
	MUL DZIELNIK	
	MOV BX, AX
	MOV AX,TIM_H	
	SUB AX, BX
	ADD AL, 48
	MOV AH,71H	;kolor
	MOV BX,898			
	MOV ES:[BX],AX


	JMP C1		;koniec wyswietlania zegara
	
ZADANIE1 PROC
 Z1:
   	MOV AL, GWIAZDKA
	MOV BX, POZYCJA_GWIAZDKI
	MOV AH,KOLOR_GWIAZDKI			
	MOV ES:[BX],AX
	DELAY 100
 	ADD POZYCJA_GWIAZDKI, 2
	MOV BX, POROWNYWANIE_GWIAZDKI
	CMP POZYCJA_GWIAZDKI, BX
	JNE Z1
	ADD POROWNYWANIE_GWIAZDKI, 160
	ADD POZYCJA_GWIAZDKI, 82
	CMP POZYCJA_GWIAZDKI, 4160
	JNE Z1
	MOV POZYCJA_GWIAZDKI, 0
	MOV POROWNYWANIE_GWIAZDKI, 78
	ADD KOLOR_GWIAZDKI, 2
	INT 1
	JMP Z1
ZADANIE1 ENDP
	
ZADANIE2 PROC
;WYZEROWANIE ZNACZNIKA ZEZWOLENIA NA PRZERWANIE
	CLI		
	ETYKIETA_POWROTU_DO_RM:
	KONTROLER_PRZERWAN_RM
	MIEKI_POWROT_RM
	POWROT_DO_RM 0,1
ZADANIE2 ENDP

PROGRAM_SIZE=$-POCZ
PROGRAM ENDS
STK	SEGMENT STACK 'STACK'
	DB 256*3 DUP(0)
STK	ENDS
END START

